### PR TITLE
Cross-version preloader

### LINKED ISSUE #16: Make preloader work across versions
The preloader implementation has a few hard-coded addresses which would make it not work in the case of an update:
https://github.com/Fexty12573/SharpPluginLoader/blob/129516ef765a8bf5796b4115c19fcd760773e999/mhw-cs-plugin-loader/Preloader.cpp#L32-L35

Instead of hard-coding `PROCESS_SECURITY_COOKIE` we should read the `SecurityCookie` address from the PE header:
image

Then, instead of checking hard-coded `SECURITY_COOKIE_INIT_GETTIME_RET ` return address, we should instead check if `return_address-some_offset` contains the default security cookie value (`0x2B992DDFA232`):
image

After we match the return address check, the client will be unpacked in memory and we can do a regular AOB scan for the `WinMain`  and `MH::sMhMain::ctor` function addresses.

### PR DESCRIPTION
**Pull request by Andoryuuta**
This change makes the preloader more resilient to version changes/updates.

* Parse PE for security cookie address
* Pattern scan for the CRT main, WinMain, and MhMain functions that it hooks.

Resolves #16.

### CODE REVIEW

File: mhw-cs-plugin-loader/Preloader.cpp [hunk 1]
```diff
@@ -26,16 +27,13 @@ SafetyHookInline g_mh_main_ctor_hook{};
...
-    const uint64_t WINMAIN = IMAGE_BASE + 0x13a4c00;
-
-}  // namespace preloader::address
-
+// The default value that MSVC uses for the IMAGE_LOAD_CONFIG_DIRECTORY64.SecurityCookie.
+const uint64_t MSVC_DEFAULT_SECURITY_COOKIE_VALUE = 0x2B992DDFA232L;
+const Pattern SCRT_COMMON_MAIN_PATTERN = Pattern::from_string("48 89 5C 24 08 57 48 83 EC 30 B9 01 00 00 00 E8 ?? ?? ?? ?? 84 C0");
+const Pattern WINMAIN_CALL_PATTERN = Pattern::from_string("E8 ?? ?? ?? ?? 0F B7 D8 E8 ?? ?? ?? ?? 4C 8B C0 44 8B CB 33 D2 48 8D ?? ?? ?? ?? ??");
+const int64_t WINMAIN_CALL_PATTERN_OFFSET = 28;
+const Pattern MHMAIN_CALL_PATTERN = Pattern::from_string("BA 00 00 08 00 48 8B CF E8 ?? ?? ?? ?? 4C 89 3F C7 87 ?? ?? ?? ?? FF FF FF FF");
```
Comment (Fexty12573) [inline mhw-cs-plugin-loader/Preloader.cpp:35]: Maybe we should think about pulling these from the AddressRepository as well. If not, there should at least be some central file to hold patterns. (Including stuff like the main update function, etc)

File: mhw-cs-plugin-loader/Preloader.cpp [hunk 2]
```diff
@@ -51,14 +49,33 @@ void open_console() {
...
+        auto load_config_directory = nt_headers->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG];
+        if (load_config_directory.VirtualAddress != 0 && load_config_directory.Size != 0)
+        {
+            IMAGE_LOAD_CONFIG_DIRECTORY64* load_config = (IMAGE_LOAD_CONFIG_DIRECTORY64*)(image_base + load_config_directory.VirtualAddress);
+            return (uint64_t*)load_config->SecurityCookie;
+        }
+    }
+
+    return nullptr;
+}
```
Comment (Fexty12573) [inline mhw-cs-plugin-loader/Preloader.cpp:69]: Code Style (Braces) 😆 Not very important, just thought I'd mention it, there's a couple inconsistencies

File: mhw-cs-plugin-loader/Preloader.cpp (hunk 1 above)
Comment (Andoryuuta) [reply mhw-cs-plugin-loader/Preloader.cpp:35]: Yeah, I'm not sure how much we want to duplicate in both the native and managed code - we basically "solved" all the same isuses in the managed code already. For these addresses, it would be nice to pull them from the address repo, scan in parallel, and cached them so that the game startup time.

Should I just lift that entire bit in to the native code and turn the managed `AddressRecords` class into a proxy to the native code?

Comment (Fexty12573) [reply mhw-cs-plugin-loader/Preloader.cpp:35]: True. Yeah I think keeping everything in native code should be fine. It could get a bit annoying with the plugin cache though. You might wanna leave that one on the managed side to not overcomplicate things.

Comment (Andoryuuta) [reply mhw-cs-plugin-loader/Preloader.cpp]: Okay, the address repo has been moved to native. Should be good for a final review now :)

File: Assets/Common/AddressRecords.json [hunk 3]
```diff
@@ -4,6 +4,21 @@
...
+    {
+        "Name": "Core::WinMainCall",
+        "Pattern": "E8 ? ? ? ? 0F B7 D8 E8 ? ? ? ? 4C 8B C0 44 8B CB 33 D2 48 8D ? ? ? ? ?",
+        "Offset": 28
+    },
+    {
+        "Name": "Core::MhMainCtor",
+        "Pattern": "BA 00 00 08 00 48 8B CF E8 ? ? ? ? 4C 89 3F C7 87 ? ? ? ? FF FF FF FF",
+        "Offset": -122
+    },
```
Comment (Fexty12573) [inline Assets/Common/AddressRecords.json:21]: Don't bother changing it, but usually I use a single `:` for separating Type:Method in this file. Not sure why I picked that but yeah, for future reference 😆

**Review by Fexty12573 — APPROVED** [review]
Looks good!
